// -*- C++ -*-
//
// generated by wxGlade 1.0.1 on Wed May 12 16:54:12 2021
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef WXGLADE_OUT_H
#define WXGLADE_OUT_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class LoginFrame: public wxFrame {
public:
    // begin wxGlade: LoginFrame::ids
    // end wxGlade

    LoginFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

// private:

// protected:
    // begin wxGlade: LoginFrame::attributes
    wxPanel* panel_1;
    wxTextCtrl* username_input;
    wxTextCtrl* password_input;
    wxButton* sign_in_button;
    wxButton* register_button;
    wxBoxSizer* login_error_message_sizer;
    // end wxGlade
}; // wxGlade: end class


class RegisterFrame: public wxFrame {
public:
    // begin wxGlade: RegisterFrame::ids
    // end wxGlade

    RegisterFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

// private:

// protected:
    // begin wxGlade: RegisterFrame::attributes
    wxPanel* panel_1;
    wxTextCtrl* username_input;
    wxTextCtrl* email_input;
    wxTextCtrl* password_input;
    wxTextCtrl* first_name_input;
    wxTextCtrl* last_name_input;
    wxTextCtrl* league_input;
    wxButton* register_button;
    wxBoxSizer* register_error_message_sizer;
    // end wxGlade
}; // wxGlade: end class


class MatchupFrame: public wxFrame {
public:
    // begin wxGlade: MatchupFrame::ids
    // end wxGlade

    MatchupFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

// private:

// protected:
    // begin wxGlade: MatchupFrame::attributes
    wxNotebook* roster_tab;
    wxPanel* notebook_1_pane_1;
    wxBoxSizer* roster_list_sizer;
    wxPanel* matchup_tab;
    wxStaticText* user_1_username;
    wxStaticText* user_1_score;
    wxStaticText* user_2_username;
    wxStaticText* user_2_score;
    wxStaticBitmap* left_arrow_fake_button;
    wxStaticText* current_date_label;
    wxButton* button_replace_pg;
    wxStaticText* name_label_left_pg;
    wxStaticText* team_label_left_pg;
    wxStaticText* game_info_label_left_pg;
    wxStaticText* stats_label_left_pg;
    wxStaticText* score_label_left_pg;
    wxStaticText* score_label_right_pg;
    wxStaticText* name_label_right_pg;
    wxStaticText* team_label_right_pg;
    wxStaticText* game_info_label_right_pg;
    wxStaticText* stats_label_right_pg;
    wxButton* button_replace_sg;
    wxStaticText* name_label_left_sg;
    wxStaticText* team_label_left_sg;
    wxStaticText* game_info_label_left_sg;
    wxStaticText* stats_label_left_sg;
    wxStaticText* score_label_left_sg;
    wxStaticText* score_label_right_sg;
    wxStaticText* name_label_right_sg;
    wxStaticText* team_label_right_sg;
    wxStaticText* game_info_label_right_sg;
    wxStaticText* stats_label_right_sg;
    wxButton* button_replace_g;
    wxStaticText* name_label_left_g;
    wxStaticText* team_label_left_g;
    wxStaticText* game_info_label_left_g;
    wxStaticText* stats_label_left_g;
    wxStaticText* score_label_left_g;
    wxStaticText* score_label_right_g;
    wxStaticText* name_label_right_g;
    wxStaticText* team_label_right_g;
    wxStaticText* game_info_label_right_g;
    wxStaticText* stats_label_right_g;
    wxButton* button_replace_sf;
    wxStaticText* name_label_left_sf;
    wxStaticText* team_label_left_sf;
    wxStaticText* game_info_label_left_sf;
    wxStaticText* stats_label_left_sf;
    wxStaticText* score_label_left_sf;
    wxStaticText* score_label_right_sf;
    wxStaticText* name_label_right_sf;
    wxStaticText* team_label_right_sf;
    wxStaticText* game_info_label_right_sf;
    wxStaticText* stats_label_right_sf;
    wxButton* button_replace_pf;
    wxStaticText* name_label_left_pf;
    wxStaticText* team_label_left_pf;
    wxStaticText* game_info_label_left_pf;
    wxStaticText* stats_label_left_pf;
    wxStaticText* score_label_left_pf;
    wxStaticText* score_label_right_pf;
    wxStaticText* name_label_right_pf;
    wxStaticText* team_label_right_pf;
    wxStaticText* game_info_label_right_pf;
    wxStaticText* stats_label_right_pf;
    wxButton* button_replace_f;
    wxStaticText* name_label_left_f;
    wxStaticText* team_label_left_f;
    wxStaticText* game_info_label_left_f;
    wxStaticText* stats_label_left_f;
    wxStaticText* score_label_left_f;
    wxStaticText* score_label_right_f;
    wxStaticText* name_label_right_f;
    wxStaticText* team_label_right_f;
    wxStaticText* game_info_label_right_f;
    wxStaticText* stats_label_right_f;
    wxButton* button_replace_c;
    wxStaticText* name_label_left_c;
    wxStaticText* team_label_left_c;
    wxStaticText* game_info_label_left_c;
    wxStaticText* stats_label_left_c;
    wxStaticText* score_label_left_c;
    wxStaticText* score_label_right_c;
    wxStaticText* name_label_right_c;
    wxStaticText* team_label_right_c;
    wxStaticText* game_info_label_right_c;
    wxStaticText* stats_label_right_c;
    wxButton* button_replace_c_1;
    wxStaticText* name_label_left_c_1;
    wxStaticText* team_label_left_c_1;
    wxStaticText* game_info_label_left_c_1;
    wxStaticText* stats_label_left_c_1;
    wxStaticText* score_label_left_c_1;
    wxStaticText* score_label_right_c_1;
    wxStaticText* name_label_right_c_1;
    wxStaticText* team_label_right_c_1;
    wxStaticText* game_info_label_right_c_1;
    wxStaticText* stats_label_right_c_1;
    wxButton* button_replace_utily;
    wxStaticText* name_label_left_util;
    wxStaticText* team_label_left_util;
    wxStaticText* game_info_label_left_util;
    wxStaticText* stats_label_left_util;
    wxStaticText* score_label_left_util;
    wxStaticText* score_label_right_util;
    wxStaticText* name_label_right_util;
    wxStaticText* team_label_right_util;
    wxStaticText* game_info_label_right_util;
    wxStaticText* stats_label_right_util;
    wxButton* button_replace_util_1;
    wxStaticText* name_label_left_util_1;
    wxStaticText* team_label_left_util_1;
    wxStaticText* game_info_label_left_util_1;
    wxStaticText* stats_label_left_util_1;
    wxStaticText* score_label_left_util_1;
    wxStaticText* score_label_right_util_1;
    wxStaticText* name_label_right_util_1;
    wxStaticText* team_label_right_util_1;
    wxStaticText* game_info_label_right_util_1;
    wxStaticText* stats_label_right_util_1;
    wxStaticText* left_daily_total_score;
    wxStaticText* right_daily_total_score;
    wxPanel* league_tab;
    // end wxGlade
}; // wxGlade: end class


class ReplaceSlotDialog: public wxDialog {
public:
    // begin wxGlade: ReplaceSlotDialog::ids
    // end wxGlade

    ReplaceSlotDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:

protected:
    // begin wxGlade: ReplaceSlotDialog::attributes
    wxBoxSizer* available_players_list_sizer;
    wxRadioButton* radio_btn_1;
    wxButton* apply_move_button;
    wxButton* cancel_move_button;
    // end wxGlade
}; // wxGlade: end class


#endif // WXGLADE_OUT_H
